/**
 * CSP y cabeceras de Firebase Hosting — alineado a OWASP ZAP baseline.
 * Sin img-src https: wildcard, sin style-src unsafe-inline (usa style-src-attr),
 * sin report-uri deprecado, COOP same-origin (auth email + Stripe redirect).
 */
export const HOSTING_CSP = [
  "default-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  [
    "img-src 'self' data: blob:",
    "https://res.cloudinary.com",
    "https://*.cloudinary.com",
    "https://images.unsplash.com",
    "https://*.supabase.co",
    "https://*.googleapis.com",
    "https://*.gstatic.com",
    "https://*.googleusercontent.com",
    "https://*.firebaseapp.com",
    "https://*.firebasestorage.app",
    "https://*.falabella.com",
    "https://*.cloudfront.net",
    "https://*.adidas.com",
    "https://*.vtexassets.com",
    "https://*.stockx.com",
    "https://www.bata.com",
    "https://cdn03.ciceksepeti.com",
    "https://dangerhype.com",
    "https://antonioperu.com",
    "https://skyshoesperu.com",
    "https://www.arstoreclub.com",
  ].join(" "),
  "font-src 'self' data: https://fonts.gstatic.com",
  "style-src 'self' https://www.gstatic.com https://fonts.googleapis.com",
  [
    "style-src-elem 'self' https://www.gstatic.com https://fonts.googleapis.com",
    // Goober CSS-in-JS (<style id="_goober">) — react-hot-toast inyecta 8 bloques CSS al cargar.
    // Chrome valida el hash del <style> en cada actualización del contenido acumulado.
    // Hashes = sha256 del contenido acumulado del elemento en cada uno de los 9 estados posibles.
    // Estados 0-2: ya cubiertos por los 3 hashes originales.
    // Estados 3-8: nuevos hashes para los 6 bloques restantes (go1268368563..go4109123758).
    "'sha256-Nqnn8clbgv+5l0PgxcTOldg8mkMKrFn4TvPL+rYUUGg='",
    "'sha256-13vrThxdyT64GcXoTNGVoRRoL0a7EGBmOJ+lemEWyws='",
    "'sha256-QZ52fjvWgIOIOPr+gRIJZ7KjzNeTBm50Z+z9dH4N1/8='",
    "'sha256-yOU6eaJ75xfag0gVFUvld5ipLRGUy94G17B1uL683EU='",
    "'sha256-OpTmykz0m3o5HoX53cykwPhUeU4OECxHQlKXpB0QJPQ='",
    "'sha256-SSIM0kI/u45y4gqkri9aH+la6wn2R+xtcBj3Lzh7qQo='",
    "'sha256-ZH/+PJIjvP1BctwYxclIuiMu1wItb0aasjpXYXOmU0Y='",
    "'sha256-58jqDtherY9NOM+ziRgSqQY0078tAZ+qtTBjMgbM9po='",
    "'sha256-7Ri/I+PfhgtpcL7hT4A0VJKI6g3pK0ZvIN09RQV4ZhI='",
  ].join(" "),
  "style-src-attr 'unsafe-inline'",
  [
    "script-src 'self'",
    "https://www.gstatic.com",
    "https://www.google.com",
    "https://www.recaptcha.net",
    "https://apis.google.com",
    "https://maps.googleapis.com",
    "https://js.stripe.com",
    "https://*.js.stripe.com",
    "https://checkout.stripe.com",
  ].join(" "),
  [
    "connect-src 'self'",
    "https://*.googleapis.com",
    "https://*.google.com",
    "https://*.firebaseapp.com",
    "https://*.firebaseio.com",
    "wss://*.firebaseio.com",
    "https://*.cloudfunctions.net",
    "https://*.supabase.co",
    "wss://*.supabase.co",
    "https://*.onrender.com",
    "https://res.cloudinary.com",
    "https://api.cloudinary.com",
    "https://api.openrouteservice.org",
    "https://www.recaptcha.net",
    "https://www.disify.com",
  ].join(" "),
  [
    "frame-src 'self'",
    "https://accounts.google.com",
    "https://*.google.com",
    "https://www.google.com",
    "https://www.recaptcha.net",
    "https://recaptcha.google.com",
    "https://js.stripe.com",
    "https://*.js.stripe.com",
    "https://hooks.stripe.com",
    "https://checkout.stripe.com",
  ].join(" "),
  "worker-src 'self' blob: https://js.stripe.com https://*.js.stripe.com",
  "upgrade-insecure-requests",
  "report-to csp-endpoint",
].join("; ");

export const HOSTING_REPORTING_ENDPOINTS =
  'csp-endpoint="https://us-central1-calzaturavilchez-ab17f.cloudfunctions.net/cspReport"';
