import { providerIdentificationParagraphs } from "@/config/businessContact";
import { complaintPlazosTerminosReferencia } from "@/domains/publico/utils/complaintLegalPlazos";
import { buildInfoProsePage, legalSections } from "../infoPageBuilders";

const PROVIDER_ID_BODY = providerIdentificationParagraphs();

export const TERMINOS_LEGAL_PAGE = buildInfoProsePage({
      group: "legal",
    kicker: "Legal",
    title: "Términos y condiciones",
    intro:
      "Los presentes Términos y Condiciones regulan el acceso y uso del sitio web de Calzatura Vilchez, la creación de cuentas de usuario y la compra de productos a través de la tienda en línea. Al registrarte, navegar o confirmar un pedido, declaras ser mayor de edad, contar con capacidad legal para contratar y aceptar íntegramente este documento, la Política de Privacidad y la Política de Cookies publicadas en el sitio.",
    accent: "Contrato de compraventa a distancia conforme a la normativa peruana",
    note: "Última actualización: 26 de mayo de 2026. Marco de referencia: Ley N.° 29571 y normas de comercio electrónico aplicables.",
    highlights: [
      "Identificación del proveedor",
      "Compra, pago y entrega",
      "Garantías y reclamos",
    ],
  sections: legalSections(
      ["1. Objeto y documentos contractuales",
        "El objeto de estos Términos y Condiciones es establecer las reglas que rigen la relación comercial entre Calzatura Vilchez, en adelante «la Empresa» o «nosotros», y el usuario o consumidor, en adelante «el Cliente» o «tú», en el marco de las ventas realizadas a través del sitio web.",
        "Forman parte integrante del contrato: (i) estos Términos y Condiciones; (ii) la Política de Privacidad; (iii) la Política de Cookies; (iv) la información descriptiva del producto, precio y disponibilidad mostrada en la ficha al momento de la compra; (v) las condiciones específicas de promociones o campañas, cuando existan; y (vi) la página de Cambios y devoluciones y el Libro de reclamaciones, para todo lo relativo a postventa.",
        "En caso de contradicción entre documentos, prevalecerá la información más favorable al consumidor cuando la ley así lo exija; en lo demás, prevalecerá el orden indicado y la confirmación de pedido.",
      ],
      ["2. Identificación del proveedor",
        ...PROVIDER_ID_BODY,
        "Sitio web: tienda en línea operada por Calzatura Vilchez, accesible desde el Perú.",
      ],
      ["3. Capacidad, registro y veracidad de los datos",
        "Los servicios de compra en línea están destinados a personas naturales mayores de dieciocho (18) años con capacidad legal para contratar.",
        "Para registrarte debes proporcionar información veraz, actual y completa (nombre, documento de identidad, correo electrónico y celular, entre otros datos solicitados). Eres responsable de mantener la confidencialidad de tus credenciales y de toda actividad realizada desde tu cuenta.",
        "La Empresa puede suspender o cancelar cuentas que presenten datos falsos, usos fraudulentos, incumplimiento de estos términos o conductas que afecten la seguridad del sitio o de otros usuarios.",
      ],
      ["4. Información de productos, precios y disponibilidad",
        "Las fotografías, descripciones, materiales, tallas y referencias de los productos tienen carácter orientativo. Procuramos que reflejen fielmente el artículo ofrecido, pero pueden existir variaciones menores de tono o textura propias del material.",
        "Los precios publicados en el sitio se expresan en soles peruanos (PEN) e incluyen el Impuesto General a las Ventas (IGV), salvo indicación expresa en contrario.",
        "La disponibilidad de stock se muestra en tiempo real o con actualización periódica. Si tras confirmar tu pedido un producto no estuviera disponible, te contactaremos para ofrecerte alternativas, sustitución o reembolso conforme a la ley.",
        "Nos reservamos el derecho de corregir errores manifestos de precio o descripción antes de la confirmación definitiva del pedido, informándote en ese caso antes de cargar el pago.",
      ],
      ["5. Proceso de compra y confirmación del pedido",
        "Para realizar una compra debes seleccionar los productos, indicar talla y cantidad, completar los datos de entrega y elegir el medio de pago habilitado.",
        "Antes de pagar podrás revisar el resumen del pedido, incluidos subtotal, costo de envío, descuentos aplicables e impuestos.",
        "El pedido se considera recibido cuando completas el proceso de pago. La confirmación contractual se perfecciona cuando el pago es aprobado por el proveedor de medios de pago o cuando aceptamos expresamente tu pedido en los casos de métodos que requieran validación manual.",
        "Recibirás una confirmación por los medios de contacto registrados (correo electrónico o notificación en tu cuenta). Conserva el número de pedido para seguimiento y reclamos.",
      ],
      ["6. Medios de pago",
        "Aceptamos pagos con tarjetas de débito y crédito de las redes habilitadas en el checkout (por ejemplo, Visa y Mastercard), procesados de forma segura a través de un proveedor de pagos autorizado.",
        "No almacenamos en nuestros servidores los datos completos de tu tarjeta. El tratamiento de datos de pago se rige por la política del proveedor de pagos y por nuestra Política de Privacidad.",
        "En caso de rechazo del pago por el emisor de la tarjeta, el pedido no será confirmado. Puedes intentar nuevamente con otro medio habilitado o contactarnos para asistencia.",
        "Los cargos aparecerán en el extracto bajo la denominación que indique el proveedor de pagos o la Empresa, según corresponda.",
      ],
      ["7. Envíos, plazos y transferencia de riesgo",
        "Realizamos envíos a distintas zonas del Perú a través de empresas de courier o medios logísticos habilitados. El costo y el plazo estimado de entrega se calculan en el checkout según la dirección indicada.",
        "Los plazos de entrega son referenciales y empiezan a contar desde la confirmación del pago y la preparación del pedido, no desde la sola fecha de compra. Pueden verse afectados por feriados, condiciones climáticas, huelgas, alta demanda estacional o causas ajenas a nuestra voluntad razonable.",
        "En Huancayo y zonas cercanas puede ofrecerse recojo en tienda o coordinación de entrega local, según disponibilidad indicada al momento de la compra.",
        "El riesgo de pérdida o daño del producto durante el transporte es asumido por la Empresa hasta la entrega al Cliente o a la persona autorizada, salvo que la ley disponga otra cosa. Si recibes un paquete visiblemente dañado, indícalo al courier y contáctanos de inmediato con evidencia fotográfica.",
      ],
      ["8. Cambios, devoluciones y desistimiento",
        "Como consumidor tienes los derechos reconocidos en la Ley N.° 29571 y normas complementarias, incluidos los relacionados con productos defectuosos, no conformes o errores de envío atribuibles a la Empresa.",
        "Las condiciones específicas de plazos, estado del producto, costos de envío en devoluciones y procedimiento se detallan en la página «Cambios y devoluciones» del sitio, que debes consultar antes de solicitar un cambio.",
        "Los productos deben devolverse en condiciones razonables de uso exclusivamente para verificación de talla en interiores, sin señales de uso en exteriores, con etiquetas cuando corresponda, salvo defecto de fábrica o error nuestro.",
        "Los reembolsos, cuando procedan, se realizarán por el mismo medio de pago utilizado o por otro medio acordado, en un plazo razonable una vez recibido y verificado el producto.",
      ],
      ["9. Garantías",
        "Los productos comercializados están sujetos a la garantía legal prevista en el Código de Protección y Defensa del Consumidor por vicios ocultos o defectos de fabricación.",
        "La garantía comercial adicional, si la hubiera, se indicará en la ficha del producto o en la comunicación de campaña. En ningún caso la garantía del fabricante o distribuidor reduce tus derechos legales como consumidor.",
      ],
      ["10. Promociones, cupones y programas de beneficios",
        "Las promociones, descuentos, cupones o beneficios del Club Vilchez están sujetos a condiciones específicas publicadas en cada campaña (vigencia, productos incluidos, montos mínimos, uso único, no acumulable, etc.).",
        "La Empresa puede modificar o finalizar campañas con previo aviso razonable en el sitio. No es posible canjear cupones vencidos o utilizados, salvo error imputable a la Empresa.",
      ],
      ["11. Uso permitido del sitio web",
        "Te concedemos una licencia limitada, no exclusiva y revocable para acceder al sitio y utilizarlo con fines personales de información y compra.",
        "Queda prohibido: copiar o extraer masivamente contenidos; utilizar robots o scripts no autorizados; intentar vulnerar la seguridad; suplantar identidad; publicar contenido ilícito; o usar el sitio con fines comerciales ajenos sin autorización escrita.",
        "Podemos restringir el acceso al sitio por mantenimiento, actualización o causas de fuerza mayor, procurando minimizar las molestias.",
      ],
      ["12. Propiedad intelectual",
        "Las marcas, logotipos, diseño, textos, fotografías, bases de datos y software del sitio son propiedad de Calzatura Vilchez o de sus licenciantes y están protegidos por la legislación peruana e internacional aplicable.",
        "Queda prohibida su reproducción, distribución, comunicación pública o transformación sin autorización previa y por escrito, salvo los usos permitidos por ley.",
      ],
      ["13. Limitación de responsabilidad",
        "La Empresa responde por el cumplimiento de sus obligaciones legales y contractuales en los términos previstos en la normativa de consumo. No excluimos ni limitamos responsabilidades que no puedan limitarse por ley.",
        "No seremos responsables por daños indirectos, lucro cesante o pérdida de datos derivados del uso del sitio cuando medie culpa del Cliente, caso fortuito o fuerza mayor, sin perjuicio de tus derechos irrenunciables como consumidor.",
        "Los enlaces a sitios de terceros se ofrecen solo para conveniencia; no controlamos ni garantizamos su contenido.",
      ],
      ["14. Protección de datos personales",
        "El tratamiento de tus datos personales se describe en la Política de Privacidad y en la Política de Cookies. Al utilizar el sitio aceptas dichos tratamientos en la medida informada y, cuando corresponda, consentida.",
      ],
      ["15. Libro de reclamaciones y solución de controversias",
        "Disponemos de un Libro de reclamaciones conforme a la Ley N.° 29571, accesible desde el enlace correspondiente en el sitio y en atención presencial.",
        "Te invitamos a contactarnos primero por WhatsApp o en tienda para resolver cualquier incidencia de forma directa. Si no obtienes respuesta satisfactoria, puedes acudir al Instituto Nacional de Defensa de la Competencia y de la Protección de la Propiedad Intelectual (Indecopi) u otras vías previstas por ley.",
        complaintPlazosTerminosReferencia(),
      ],
      ["16. Ley aplicable y jurisdicción",
        "Estos Términos y Condiciones se rigen por las leyes de la República del Perú.",
        "Cualquier controversia se someterá a los tribunales competentes del domicilio del consumidor o del lugar de cumplimiento de la obligación, según las normas de protección al consumidor y de competencia territorial aplicables.",
      ],
      ["17. Modificaciones",
        "Podemos actualizar estos Términos y Condiciones para reflejar cambios legales, comerciales o tecnológicos. La versión vigente estará publicada en esta página con su fecha de actualización.",
        "Los cambios no afectarán retroactivamente pedidos ya confirmados, salvo disposición legal imperativa. El uso continuado del sitio tras la publicación de cambios sustanciales implicará tu aceptación de la nueva versión.",
      ]
  ),
  faq: [
      {
        question: "¿Cuándo se confirma mi pedido?",
        answer:
          "Cuando el pago es aprobado por el proveedor de medios de pago o cuando validamos manualmente el método elegido. Recibirás confirmación con el número de pedido para seguimiento.",
      },
      {
        question: "¿Puedo cancelar un pedido después de pagar?",
        answer:
          "Puedes solicitarlo de inmediato por WhatsApp. Si el pedido no ha sido despachado, gestionamos la cancelación y el reembolso según el medio de pago. Si ya fue enviado, aplican las reglas de cambios y devoluciones.",
      },
      {
        question: "¿Qué hago si recibo un producto equivocado o defectuoso?",
        answer:
          "Contáctanos dentro del plazo indicado en Cambios y devoluciones, con fotos y número de pedido. Evaluamos reemplazo, cambio de talla o reembolso según corresponda y la normativa de consumo.",
      },
      {
        question: "¿Los precios incluyen IGV?",
        answer:
          "Sí, salvo que en la ficha del producto o en la campaña se indique expresamente lo contrario. El total a pagar se muestra en el resumen antes de confirmar la compra.",
      },
    ],
});
